## National Dataset Merging

In [48]:
import pandas as pd

country_tc_loss = pd.read_csv(r"C:\Users\hanif\Downloads\Data Analyst\Project\end-to-end\Indonesia Deforestation & Wildfire Analysis (2001–2024)\indonesia-deforestation-wildfire-analysis\data\processed\country_tree_cover_loss.csv")
country_primary_loss = pd.read_csv(r"C:\Users\hanif\Downloads\Data Analyst\Project\end-to-end\Indonesia Deforestation & Wildfire Analysis (2001–2024)\indonesia-deforestation-wildfire-analysis\data\processed\country_primary_loss.csv")
carbon_gross_emissions = pd.read_csv(r"C:\Users\hanif\Downloads\Data Analyst\Project\end-to-end\Indonesia Deforestation & Wildfire Analysis (2001–2024)\indonesia-deforestation-wildfire-analysis\data\processed\carbon_gross_emissions.csv")

In [50]:
country_tc_loss.head()

     country  threshold  year  tree_cover_loss_ha
0  Indonesia         30  2001              744084
1  Indonesia         30  2002              855270
2  Indonesia         30  2003              544812
3  Indonesia         30  2004             1289035
4  Indonesia         30  2005             1182436

In [52]:
country_primary_loss.head()

     country  threshold  year  tree_cover_loss_ha
0  Indonesia         30  2002              271745
1  Indonesia         30  2003              248436
2  Indonesia         30  2004              479153
3  Indonesia         30  2005              478404
4  Indonesia         30  2006              468381

In [54]:
carbon_gross_emissions.head()

     country  year  gross_emissions_Mg_CO2e
0  Indonesia  2001                508698553
1  Indonesia  2002                650458057
2  Indonesia  2003                444613985
3  Indonesia  2004               1011614959
4  Indonesia  2005                976236940

## Merge Country Tree Cover Loss & Country Primary Loss

In [57]:
national = pd.merge(
    country_tc_loss,
    country_primary_loss,
    on=["country", "year"],
    how="inner"
)

national.head()

,country,threshold_x,year,tree_cover_loss_ha_x,threshold_y,tree_cover_loss_ha_y
0,Indonesia,30,2002,855270,30,271745
1,Indonesia,30,2003,544812,30,248436
2,Indonesia,30,2004,1289035,30,479153
3,Indonesia,30,2005,1182436,30,478404
4,Indonesia,30,2006,1433147,30,468381

## Merge National data with carbon_gross_emissions data

In [60]:
national = pd.merge(
    national,
    carbon_gross_emissions,
    on = ["country","year"],
    how = "inner"
)

national.head()

,country,threshold_x,year,tree_cover_loss_ha_x,threshold_y,tree_cover_loss_ha_y,gross_emissions_Mg_CO2e
0,Indonesia,30,2002,855270,30,271745,650458057
1,Indonesia,30,2003,544812,30,248436,444613985
2,Indonesia,30,2004,1289035,30,479153,1011614959
3,Indonesia,30,2005,1182436,30,478404,976236940
4,Indonesia,30,2006,1433147,30,468381,1050082785

In [62]:
national.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   country                  24 non-null     object
 1   threshold_x              24 non-null     int64
 2   year                     24 non-null     int64
 3   tree_cover_loss_ha_x     24 non-null     int64
 4   threshold_y              24 non-null     int64
 5   tree_cover_loss_ha_y     24 non-null     int64
 6   gross_emissions_Mg_CO2e  24 non-null     int64
dtypes: int64(6), object(1)
memory usage: 1.4+ KB

## Save to CSV

In [66]:
national_def = national [[
    "country", "year","tree_cover_loss_ha_x", "tree_cover_loss_ha_y", "gross_emissions_Mg_CO2e"]]

In [68]:
national_def.head()

,country,year,tree_cover_loss_ha_x,tree_cover_loss_ha_y,gross_emissions_Mg_CO2e
0,Indonesia,2002,855270,271745,650458057
1,Indonesia,2003,544812,248436,444613985
2,Indonesia,2004,1289035,479153,1011614959
3,Indonesia,2005,1182436,478404,976236940
4,Indonesia,2006,1433147,468381,1050082785

In [70]:
national_def.rename(
    columns={
        "tree_cover_loss_ha_x":"tc_loss_ha",
        "tree_cover_loss_ha_y":"primary_loss_ha"}
)

      country  year  tc_loss_ha  primary_loss_ha  gross_emissions_Mg_CO2e
0   Indonesia  2002      855270           271745                650458057
1   Indonesia  2003      544812           248436                444613985
2   Indonesia  2004     1289035           479153               1011614959
3   Indonesia  2005     1182436           478404                976236940
4   Indonesia  2006     1433147           468381               1050082785
5   Indonesia  2007     1387621           525992               1196562039
6   Indonesia  2008     1396246           469405               1053966407
7   Indonesia  2009     1944957           683826               1439965694
8   Indonesia  2010     1279328           540976               1058708908
9   Indonesia  2011     1543628           613905               1257346845
10  Indonesia  2012     2260258           855533               1812271450
11  Indonesia  2013     1139300           472992                884816294
12  Indonesia  2014     1894359           736797               1439689263
13  Indonesia  2015     1746464           666637               1286444341
14  Indonesia  2016     2422066           928658               1849379881
15  Indonesia  2017     1300718           373255                843656546
16  Indonesia  2018     1218733           339888                776780749
17  Indonesia  2019     1176883           323646                754598044
18  Indonesia  2020      961585           270057                604785145
19  Indonesia  2021      841390           202906                518185901
20  Indonesia  2022      885237           230003                549418240
21  Indonesia  2023     1395285           292374                853323054
22  Indonesia  2024     1120264           258812                690608784
23  Indonesia  2025     1161831           295596                735560123

In [89]:
national_def.to_csv(r'C:\Users\hanif\Downloads\Data Analyst\Project\end-to-end\Indonesia Deforestation & Wildfire Analysis (2001–2024)\indonesia-deforestation-wildfire-analysis\data\processed\national_deforestation.csv')

In [91]:
df=pd.read_csv(r"C:\Users\hanif\Downloads\Data Analyst\Project\end-to-end\Indonesia Deforestation & Wildfire Analysis (2001–2024)\indonesia-deforestation-wildfire-analysis\data\processed\national_deforestation.csv")
df.head()

,Unnamed: 0,country,year,tree_cover_loss_ha_x,tree_cover_loss_ha_y,gross_emissions_Mg_CO2e
0,0,Indonesia,2002,855270,271745,650458057
1,1,Indonesia,2003,544812,248436,444613985
2,2,Indonesia,2004,1289035,479153,1011614959
3,3,Indonesia,2005,1182436,478404,976236940
4,4,Indonesia,2006,1433147,468381,1050082785

In [93]:
df.drop(columns="Unnamed: 0", inplace=True)

In [95]:
df.to_csv(r"C:\Users\hanif\Downloads\Data Analyst\Project\end-to-end\Indonesia Deforestation & Wildfire Analysis (2001–2024)\indonesia-deforestation-wildfire-analysis\data\processed\national_deforestation.csv", index=False)

## Province Dataset Merging

In [22]:
import pandas as pd

subnational_tc_loss = pd.read_csv(r"C:\Users\hanif\Downloads\Data Analyst\Project\end-to-end\Indonesia Deforestation & Wildfire Analysis (2001–2024)\indonesia-deforestation-wildfire-analysis\data\processed\subnational_1_tree_cover_loss.csv")
subnational_carbon_gross_emissions = pd.read_csv(r"C:\Users\hanif\Downloads\Data Analyst\Project\end-to-end\Indonesia Deforestation & Wildfire Analysis (2001–2024)\indonesia-deforestation-wildfire-analysis\data\processed\subnational_1_carbon_gross_emissions.csv")

In [24]:
subnational_tc_loss.head()

     country     subnational1  threshold  year  tree_cover_loss_ha
0  Indonesia             Aceh         30  2001               18278
1  Indonesia             Bali         30  2001                 424
2  Indonesia  Bangka Belitung         30  2001               13910
3  Indonesia           Banten         30  2001                1054
4  Indonesia         Bengkulu         30  2001               14198

In [28]:
subnational_tc_loss.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 850 entries, 0 to 849
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   country             850 non-null    object
 1   subnational1        850 non-null    object
 2   threshold           850 non-null    int64
 3   year                850 non-null    int64
 4   tree_cover_loss_ha  850 non-null    int64
dtypes: int64(3), object(2)
memory usage: 33.3+ KB

In [26]:
subnational_carbon_gross_emissions.head()

     country     subnational1  year  gross_emissions_Mg_CO2e
0  Indonesia             Aceh  2001                 10876310
1  Indonesia             Bali  2001                   260474
2  Indonesia  Bangka Belitung  2001                  7031487
3  Indonesia           Banten  2001                   626102
4  Indonesia         Bengkulu  2001                 10203132

In [30]:
subnational_carbon_gross_emissions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 850 entries, 0 to 849
Data columns (total 4 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   country                  850 non-null    object
 1   subnational1             850 non-null    object
 2   year                     850 non-null    int64
 3   gross_emissions_Mg_CO2e  850 non-null    int64
dtypes: int64(2), object(2)
memory usage: 26.7+ KB

In [98]:
province = pd.merge(
    subnational_tc_loss,
    subnational_carbon_gross_emissions,
    on = ["subnational1","country","year"],
    how = "inner"
)

province.head()

,country,subnational1,threshold,year,tree_cover_loss_ha,gross_emissions_Mg_CO2e
0,Indonesia,Aceh,30,2001,18278,10876310
1,Indonesia,Bali,30,2001,424,260474
2,Indonesia,Bangka Belitung,30,2001,13910,7031487
3,Indonesia,Banten,30,2001,1054,626102
4,Indonesia,Bengkulu,30,2001,14198,10203132

In [100]:
province.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 850 entries, 0 to 849
Data columns (total 6 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   country                  850 non-null    object
 1   subnational1             850 non-null    object
 2   threshold                850 non-null    int64
 3   year                     850 non-null    int64
 4   tree_cover_loss_ha       850 non-null    int64
 5   gross_emissions_Mg_CO2e  850 non-null    int64
dtypes: int64(4), object(2)
memory usage: 40.0+ KB

## Save to CSV

In [102]:
province.drop(columns="threshold", inplace=True)

In [104]:
province.to_csv(r"C:\Users\hanif\Downloads\Data Analyst\Project\end-to-end\Indonesia Deforestation & Wildfire Analysis (2001–2024)\indonesia-deforestation-wildfire-analysis\data\processed\province_deforestation.csv", index=False)

In [107]:
df=pd.read_csv(r"C:\Users\hanif\Downloads\Data Analyst\Project\end-to-end\Indonesia Deforestation & Wildfire Analysis (2001–2024)\indonesia-deforestation-wildfire-analysis\data\processed\province_deforestation.csv")
df.head()

,country,subnational1,year,tree_cover_loss_ha,gross_emissions_Mg_CO2e
0,Indonesia,Aceh,2001,18278,10876310
1,Indonesia,Bali,2001,424,260474
2,Indonesia,Bangka Belitung,2001,13910,7031487
3,Indonesia,Banten,2001,1054,626102
4,Indonesia,Bengkulu,2001,14198,10203132