# Wildfire Data Cleaning

## Load Data

In [4]:
import pandas as pd

df = pd.read_csv(r'C:\Users\hanif\Downloads\Data Analyst\Project\end-to-end\Indonesia Deforestation & Wildfire Analysis (2001–2024)\indonesia-deforestation-wildfire-analysis\data\processed\wildfire_raw_merge.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1515564 entries, 0 to 1515563
Data columns (total 15 columns):
 #   Column      Non-Null Count    Dtype
---  ------      --------------    -----
 0   latitude    1515564 non-null  float64
 1   longitude   1515564 non-null  float64
 2   brightness  1515564 non-null  float64
 3   scan        1515564 non-null  float64
 4   track       1515564 non-null  float64
 5   acq_date    1515564 non-null  object
 6   acq_time    1515564 non-null  int64
 7   satellite   1515564 non-null  object
 8   instrument  1515564 non-null  object
 9   confidence  1515564 non-null  int64
 10  version     1515564 non-null  float64
 11  bright_t31  1515564 non-null  float64
 12  frp         1515564 non-null  float64
 13  daynight    1515564 non-null  object
 14  type        1515564 non-null  int64
dtypes: float64(8), int64(3), object(4)
memory usage: 173.4+ MB

In [10]:
df.describe()

,latitude,longitude,brightness,scan,track,acq_time,confidence,version,bright_t31,frp,type
count,1.515564e+06,1.515564e+06,1.515564e+06,1.515564e+06,1.515564e+06,1.515564e+06,1.515564e+06,1.515564e+06,1.515564e+06,1.515564e+06,1.515564e+06
mean,-2.219187e+00,1.117996e+02,3.229397e+02,1.524663e+00,1.185334e+00,7.561499e+02,6.502238e+01,8.919503e+00,2.955856e+02,3.441566e+01,1.076378e-01
std,3.112058e+00,9.588689e+00,1.544743e+01,7.325554e-01,2.290794e-01,4.816519e+02,2.253869e+01,1.194843e+01,6.667644e+00,7.076472e+01,4.448187e-01
min,-1.090640e+01,9.506800e+01,3.000000e+02,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,6.030000e+00,2.662000e+02,0.000000e+00,0.000000e+00
25%,-3.290200e+00,1.038640e+02,3.136000e+02,1.000000e+00,1.000000e+00,5.140000e+02,5.100000e+01,6.200000e+00,2.920000e+02,1.020000e+01,0.000000e+00
50%,-2.160500e+00,1.113095e+02,3.199000e+02,1.200000e+00,1.100000e+00,6.110000e+02,6.700000e+01,6.200000e+00,2.958000e+02,1.770000e+01,0.000000e+00
75%,1.246000e-01,1.158699e+02,3.282000e+02,1.700000e+00,1.300000e+00,7.030000e+02,8.100000e+01,6.200000e+00,2.999000e+02,3.480000e+01,0.000000e+00
max,5.833100e+00,1.409773e+02,5.071000e+02,4.800000e+00,2.000000e+00,2.351000e+03,1.000000e+02,6.103000e+01,4.001000e+02,6.647600e+03,3.000000e+00

In [6]:
df.head()

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_t31,frp,daynight,type
0,-3.0334,133.0733,317.4,1.0,1.0,2000-11-01,151,Terra,MODIS,63,6.2,300.9,8.2,D,0
1,1.2473,109.6869,318.1,1.0,1.0,2000-11-01,328,Terra,MODIS,59,6.2,294.9,9.7,D,0
2,1.3812,100.1306,313.9,3.4,1.7,2000-11-01,329,Terra,MODIS,45,6.2,277.1,50.3,D,0
3,0.8381,101.5897,346.1,2.5,1.5,2000-11-01,329,Terra,MODIS,94,6.2,293.5,186.0,D,0
4,0.8349,101.6121,335.3,2.5,1.5,2000-11-01,329,Terra,MODIS,88,6.2,294.2,115.5,D,0

## Check Missing Value

In [13]:
df.isnull().sum()

latitude      0
longitude     0
brightness    0
scan          0
track         0
acq_date      0
acq_time      0
satellite     0
instrument    0
confidence    0
version       0
bright_t31    0
frp           0
daynight      0
type          0
dtype: int64

## Check Duplicate

In [18]:
df.duplicated().sum()

0

## Convert Date

In [35]:
import numpy as np

df['acq_date'] = pd.to_datetime(df['acq_date'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1515564 entries, 0 to 1515563
Data columns (total 15 columns):
 #   Column      Non-Null Count    Dtype
---  ------      --------------    -----
 0   latitude    1515564 non-null  float64
 1   longitude   1515564 non-null  float64
 2   brightness  1515564 non-null  float64
 3   scan        1515564 non-null  float64
 4   track       1515564 non-null  float64
 5   acq_date    1515564 non-null  datetime64[ns]
 6   acq_time    1515564 non-null  int64
 7   satellite   1515564 non-null  object
 8   instrument  1515564 non-null  object
 9   confidence  1515564 non-null  int64
 10  version     1515564 non-null  float64
 11  bright_t31  1515564 non-null  float64
 12  frp         1515564 non-null  float64
 13  daynight    1515564 non-null  object
 14  type        1515564 non-null  int64
dtypes: datetime64[ns](1), float64(8), int64(3), object(3)
memory usage: 173.4+ MB

## Create Year & Month Columns

In [38]:
df['year']=df['acq_date'].dt.year
df['month']=df['acq_date'].dt.month

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1515564 entries, 0 to 1515563
Data columns (total 17 columns):
 #   Column      Non-Null Count    Dtype
---  ------      --------------    -----
 0   latitude    1515564 non-null  float64
 1   longitude   1515564 non-null  float64
 2   brightness  1515564 non-null  float64
 3   scan        1515564 non-null  float64
 4   track       1515564 non-null  float64
 5   acq_date    1515564 non-null  datetime64[ns]
 6   acq_time    1515564 non-null  int64
 7   satellite   1515564 non-null  object
 8   instrument  1515564 non-null  object
 9   confidence  1515564 non-null  int64
 10  version     1515564 non-null  float64
 11  bright_t31  1515564 non-null  float64
 12  frp         1515564 non-null  float64
 13  daynight    1515564 non-null  object
 14  type        1515564 non-null  int64
 15  year        1515564 non-null  int32
 16  month       1515564 non-null  int32
dtypes: datetime64[ns](1), float64(8), int32(2), int64(3), object(3)
memory usage: 185.0+ MB

## Check Confidence Distribution

In [42]:
df['confidence'].describe()

count    1.515564e+06
mean     6.502238e+01
std      2.253869e+01
min      0.000000e+00
25%      5.100000e+01
50%      6.700000e+01
75%      8.100000e+01
max      1.000000e+02
Name: confidence, dtype: float64

## Filter vegetation fire type

In [61]:
df = df[df['type']==0]

In [73]:
df['type'].describe()

count    649269.0
mean          0.0
std           0.0
min           0.0
25%           0.0
50%           0.0
75%           0.0
max           0.0
Name: type, dtype: float64

## Select Relevat Columns

In [76]:
df = df[
    [
        "latitude",
        "longitude",
        "acq_date",
        "acq_time",
        "satellite",
        "brightness",
        "bright_t31",
        "confidence",
        "frp",
        "daynight",
        "year",
        "month"
    ]
]

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 649269 entries, 3 to 1515559
Data columns (total 12 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   latitude    649269 non-null  float64
 1   longitude   649269 non-null  float64
 2   acq_date    649269 non-null  datetime64[ns]
 3   acq_time    649269 non-null  int64
 4   satellite   649269 non-null  object
 5   brightness  649269 non-null  float64
 6   bright_t31  649269 non-null  float64
 7   confidence  649269 non-null  int64
 8   frp         649269 non-null  float64
 9   daynight    649269 non-null  object
 10  year        649269 non-null  int32
 11  month       649269 non-null  int32
dtypes: datetime64[ns](1), float64(5), int32(2), int64(2), object(2)
memory usage: 59.4+ MB

In [83]:
df.to_csv(r'C:\Users\hanif\Downloads\Data Analyst\Project\end-to-end\Indonesia Deforestation & Wildfire Analysis (2001–2024)\indonesia-deforestation-wildfire-analysis\data\processed\wildfire_cleaned.csv')

In [89]:
dfa = pd.read_csv(r'C:\Users\hanif\Downloads\Data Analyst\Project\end-to-end\Indonesia Deforestation & Wildfire Analysis (2001–2024)\indonesia-deforestation-wildfire-analysis\data\processed\wildfire_cleaned.csv')

dfa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 649269 entries, 0 to 649268
Data columns (total 13 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   Unnamed: 0  649269 non-null  int64
 1   latitude    649269 non-null  float64
 2   longitude   649269 non-null  float64
 3   acq_date    649269 non-null  object
 4   acq_time    649269 non-null  int64
 5   satellite   649269 non-null  object
 6   brightness  649269 non-null  float64
 7   bright_t31  649269 non-null  float64
 8   confidence  649269 non-null  int64
 9   frp         649269 non-null  float64
 10  daynight    649269 non-null  object
 11  year        649269 non-null  int64
 12  month       649269 non-null  int64
dtypes: float64(5), int64(5), object(3)
memory usage: 64.4+ MB