# Load Data

In [5]:
import pandas as pd
import glob

files = glob.glob(
    r"C:\Users\hanif\Downloads\Data Analyst\Project\end-to-end\Indonesia Deforestation & Wildfire Analysis (2001–2024)\indonesia-deforestation-wildfire-analysis\data\raw\nasa_firms_modis\*.csv"
)

print(files[:5])

['C:\\Users\\hanif\\Downloads\\Data Analyst\\Project\\end-to-end\\Indonesia Deforestation & Wildfire Analysis (2001–2024)\\indonesia-deforestation-wildfire-analysis\\data\\raw\\nasa_firms_modis\\modis_2000_Indonesia.csv', 'C:\\Users\\hanif\\Downloads\\Data Analyst\\Project\\end-to-end\\Indonesia Deforestation & Wildfire Analysis (2001–2024)\\indonesia-deforestation-wildfire-analysis\\data\\raw\\nasa_firms_modis\\modis_2001_Indonesia.csv', 'C:\\Users\\hanif\\Downloads\\Data Analyst\\Project\\end-to-end\\Indonesia Deforestation & Wildfire Analysis (2001–2024)\\indonesia-deforestation-wildfire-analysis\\data\\raw\\nasa_firms_modis\\modis_2002_Indonesia.csv', 'C:\\Users\\hanif\\Downloads\\Data Analyst\\Project\\end-to-end\\Indonesia Deforestation & Wildfire Analysis (2001–2024)\\indonesia-deforestation-wildfire-analysis\\data\\raw\\nasa_firms_modis\\modis_2003_Indonesia.csv', 'C:\\Users\\hanif\\Downloads\\Data Analyst\\Project\\end-to-end\\Indonesia Deforestation & Wildfire Analysis (2001–2024)\\indonesia-deforestation-wildfire-analysis\\data\\raw\\nasa_firms_modis\\modis_2004_Indonesia.csv']

# Merge Data

In [7]:
# merge semua file csv
df = pd.concat(
    [pd.read_csv(file) for file in files],
    ignore_index=True
)

# lihat ukuran dataset
print(df.shape)

(1515564, 15)

In [9]:
df.head()

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_t31,frp,daynight,type
0,-3.0334,133.0733,317.4,1.0,1.0,2000-11-01,151,Terra,MODIS,63,6.2,300.9,8.2,D,0
1,1.2473,109.6869,318.1,1.0,1.0,2000-11-01,328,Terra,MODIS,59,6.2,294.9,9.7,D,0
2,1.3812,100.1306,313.9,3.4,1.7,2000-11-01,329,Terra,MODIS,45,6.2,277.1,50.3,D,0
3,0.8381,101.5897,346.1,2.5,1.5,2000-11-01,329,Terra,MODIS,94,6.2,293.5,186.0,D,0
4,0.8349,101.6121,335.3,2.5,1.5,2000-11-01,329,Terra,MODIS,88,6.2,294.2,115.5,D,0

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1515564 entries, 0 to 1515563
Data columns (total 15 columns):
 #   Column      Non-Null Count    Dtype
---  ------      --------------    -----
 0   latitude    1515564 non-null  float64
 1   longitude   1515564 non-null  float64
 2   brightness  1515564 non-null  float64
 3   scan        1515564 non-null  float64
 4   track       1515564 non-null  float64
 5   acq_date    1515564 non-null  object
 6   acq_time    1515564 non-null  int64
 7   satellite   1515564 non-null  object
 8   instrument  1515564 non-null  object
 9   confidence  1515564 non-null  int64
 10  version     1515564 non-null  float64
 11  bright_t31  1515564 non-null  float64
 12  frp         1515564 non-null  float64
 13  daynight    1515564 non-null  object
 14  type        1515564 non-null  int64
dtypes: float64(8), int64(3), object(4)
memory usage: 173.4+ MB

# Save Data Merge to CSV

In [22]:
df.to_csv(r'C:\Users\hanif\Downloads\Data Analyst\Project\end-to-end\Indonesia Deforestation & Wildfire Analysis (2001–2024)\indonesia-deforestation-wildfire-analysis\data\processed\wildfire_raw_merge.csv', index=False)

print("Merge Complete")

Merge Complete

In [29]:
import pandas
dfm=pandas.read_csv(r'C:\Users\hanif\Downloads\Data Analyst\Project\end-to-end\Indonesia Deforestation & Wildfire Analysis (2001–2024)\indonesia-deforestation-wildfire-analysis\data\processed\wildfire_raw_merge.csv')

dfm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1515564 entries, 0 to 1515563
Data columns (total 15 columns):
 #   Column      Non-Null Count    Dtype
---  ------      --------------    -----
 0   latitude    1515564 non-null  float64
 1   longitude   1515564 non-null  float64
 2   brightness  1515564 non-null  float64
 3   scan        1515564 non-null  float64
 4   track       1515564 non-null  float64
 5   acq_date    1515564 non-null  object
 6   acq_time    1515564 non-null  int64
 7   satellite   1515564 non-null  object
 8   instrument  1515564 non-null  object
 9   confidence  1515564 non-null  int64
 10  version     1515564 non-null  float64
 11  bright_t31  1515564 non-null  float64
 12  frp         1515564 non-null  float64
 13  daynight    1515564 non-null  object
 14  type        1515564 non-null  int64
dtypes: float64(8), int64(3), object(4)
memory usage: 173.4+ MB

# Load Data Merge

In [31]:
dfm.head()

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_t31,frp,daynight,type
0,-3.0334,133.0733,317.4,1.0,1.0,2000-11-01,151,Terra,MODIS,63,6.2,300.9,8.2,D,0
1,1.2473,109.6869,318.1,1.0,1.0,2000-11-01,328,Terra,MODIS,59,6.2,294.9,9.7,D,0
2,1.3812,100.1306,313.9,3.4,1.7,2000-11-01,329,Terra,MODIS,45,6.2,277.1,50.3,D,0
3,0.8381,101.5897,346.1,2.5,1.5,2000-11-01,329,Terra,MODIS,94,6.2,293.5,186.0,D,0
4,0.8349,101.6121,335.3,2.5,1.5,2000-11-01,329,Terra,MODIS,88,6.2,294.2,115.5,D,0